spring:
  application:
    name: 'devpilot-ai'
  r2dbc:
    url:  'r2dbc:postgresql://localhost:5432/devpilot'
    username: 'devpilot'
    password: 'devpilot'
  data:
    redis:
      host: localhost
      port: 6379

server:
  port: 8080

logging:
  level:
    org.springframework.web.reactive.function.client: DEBUG
